apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecr-app-underwater
  labels:
    app: underwater
spec:
  selector:
    matchLabels:
        app: underwater
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: underwater
    spec:
      containers:
        - name: underwater
          image: 292602749294.dkr.ecr.ap-south-1.amazonaws.com/underwater:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          
